### PR TITLE
Closes #36: setup static site with Asciidoctor + Travis-CI

### LINKED ISSUE #36: generate static site
Options:

Jekyll
https://github.com/asciidoctor/jekyll-asciidoc
https://github.com/asciidoctor/jekyll-asciidoc-quickstart

Antora
https://docs.antora.org/antora/2.1/run-antora/

### PR DESCRIPTION
**Pull request by capsulecorplab**
Closes #36 

Updates to `README.adoc` on `master` branch will now trigger a [Travis-CI build](https://travis-ci.com/LearnTeachCode/code-coffee-compendium/builds) to generate a static site on https://learnteachcode.org/code-coffee-compendium/, using the [asciidoctor](https://asciidoctor.org/) toolchain, hosted with GitHub pages.

### CODE REVIEW

**Comment by cynful** [comment]
lgtm!
one question though: is there a reason that we've picked travis vs github actions?
I feel that the argument for github actions is, that its more native?

**Comment by LearningNerd** [comment]
We could do GitHub Actions too, for sure :) @capsulecorplab are you familiar with both? any pros/cons? As far as I know both have the basic features we would need. Doesn't really matter to me which we use. :)

**Comment by capsulecorplab** [comment]
GitHub has built-in CI/CD now?! :astonished: 
It looks like [CI/CD support on GH Actions](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/) was just introduced in November of 2019. I haven't worked with it, so I don't know how stable it is... I'm leaning toward sticking w/ Travis-CI for now (since it works), but open to migrating it to GH actions later, if someone else wants to work on that PR.

**Comment by cynful** [comment]
its more native, especially since github actions will auto generate a GH_TOKEN for the repo

**Comment by cynful** [comment]
give me until this weekend, if I haven't made a workflow, I'll launch it

**Comment by capsulecorplab** [comment]
@cynful I haven't had time to read up on GH actions. Could we merge this for now (since it works), then open a separate issue/PR for publishing to gh-pages w/ GH actions? That way we don't have to continuously rebase this branch off `master`, if we have any (incoming) additions made to the repo.

**Pull request merged**
